'use strict';

module.exports = {
  BASE_CURRENCY_INDICATOR: 1,
  ACTIVE: 1,
  INACTIVE_LOT_STATUS: 0,
  PROVISIONED_LOT_STATUS: 1,
  INACTIVE_CARD_STATUS: 0,
  ACTIVE_CARD_STATUS: 1,
  USED_CARD_STATUS: 2,
  TABLE_ACCESS_CONTROL_ID_FOR_CARD: 1,
  LOCKED: 1,
  SYNC_CARD_GENERATE_PARAM_NAME: 'sync_card_generate',
  SYNC_CARD_GENERATE_ENABLED: '1',
  CANCELLED_CARD_TRANSFER_STATUS: 0,
  ACCEPTED_CARD_TRANSFER_STATUS: 1,
  PENDING_CARD_TRANSFER_STATUS: 2,
  CARD_GENERATION_FAILED: 0,
  CARD_GENERATION_SUCCESS: 1,
  DEFAULT_SALES_DISCONTINUE_DATE_TIME: '9999-12-31 00:00:00'
};